services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.9.1
    container_name: caddy
    hostname: caddy
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./index.html:/srv/index.html
      - ./sub:/srv/sub
      - caddy-data:/data

volumes:
  caddy-data:
